### ISSUE TITLE
hostmanager and multi provider - override not working

### ISSUE THREAD

**Issue by phpPhil** [devopsgroup-io/vagrant-hostmanager#149]
In a multi provider vagrant file I'm trying to enable the hostmanager plugin only for Virtualbox via overwrite:

```
config.hostmanager.enabled = false
...
config.vm.provider "virtualbox" do |vb|
    vb.hostmanager.enabled = true
    ...
end
config.vm.provider "azure" do |azure|
    # do nothing
    ...
end
```

However, vagrant complains about it:

```
There are errors in the configuration of this machine. Please fix the following errors and try again:

VirtualBox Provider:
* The following settings shouldn't exist: hostmanager
```

I also tried...

```
config.vm.provider "virtualbox" do |vb,override|
    override.hostmanager.enabled = true
    ...
end
```

This doesn't throw an error but it also doesn't run hostmanager. It looks like override on the hostmanager plugin is not supported or broken.

This is a show stopper for multi provider setups. Is there a workaround for this?

**Comment by seth-reeser** [comment]
Is the block wrapped in:
````
Vagrant.configure("2") do |config|
    config.hostmanager.enabled = true
    config.vm.provider "virtualbox" do |vb|
        ...
    end
    config.vm.provider "azure" do |azure|
        ...
    end
end
````

**Comment by phpPhil** [comment]
@seth-reeser : Sorry, man - I never answered your recommendation, also great you labelled it.
Now, many years later... I can't remember what I did and how I resolved it. Thank you, anyway :)

Closing this thread.
