### ISSUE TITLE
was not found configured for this Vagrant

### ISSUE THREAD

**Issue by lbfxq** [devopsgroup-io/vagrant-hostmanager#187]
i have tow box,
the first box up is right.
the second box up  is error.
the error msg is "was not found configured for this Vagrant";

the second box commend:
[]vagrant box add php7 ubuntu.box
[]vagrant init --output php7 php7
[]vagrant up php7

who help me?

**Comment by seth-reeser** [comment]
Please provide your Vagrantfile for troubleshooting.
