### ISSUE TITLE
Hosts file entries not found by El Capitan browsers

### ISSUE THREAD

**Issue by 3hats** [devopsgroup-io/vagrant-hostmanager#215]
After a couple of reboots related to mouse issue, I can't get to my development Linux server from Mac desktop browsers. I can ping normally but local URL in browser gives "server not found" error.

The Host file looks normal and edits and saves to it didn't fix problem.

Help!

**Comment by seth-reeser** [comment]
Please rebuild your virtual machine and verify, firewall, SELinux, etc. Seems like a service related issue.
