### ISSUE TITLE
em::Ext::BuildError: ERROR: Failed to build gem native extension.

### ISSUE THREAD

**Issue by Kaosh** [devopsgroup-io/vagrant-hostmanager#218]
I cant make new jekyll site. please help.
![screenshot from 2016-11-18 15 43 29](https://cloud.githubusercontent.com/assets/17171560/20416807/fdb5530e-ada5-11e6-8ca7-69f66a0b621d.png)

**Comment by seth-reeser** [comment]
Hi @Kaosh, this seems to be unrelated. Please open your issue at https://github.com/jekyll/jekyll

**Comment by vhosakot** [comment]
I saw the error `Failed to build gem native extension` too on CentOS 7.3 and vagrant 1.8.7.

I resolved it after installing ruby-devel and gcc (`yum -y install ruby-devel gcc`)
