### ISSUE TITLE
Vagrant 1.9 compability

### ISSUE THREAD

**Issue by dominikzogg** [devopsgroup-io/vagrant-hostmanager#220]
After upgrading to vagrant 1.9 i get the message that vagrant-hostmanager is not available

**Comment by amontalban** [comment]
Hi @dominikzogg,

It works for me, have you tried to do: `vagrant plugin expunge --reinstall` after upgrade?

Thanks!

**Comment by seth-reeser** [comment]
Yes please run `vagrant plugin expunge --reinstall` if you cannot reinstall, please reopen this issue.

**Comment by dominikzogg** [comment]
@amontalban @seth-reeser perfect, works
