### ISSUE TITLE
vagrant-hostmanager missing

### ISSUE THREAD

**Issue by codecowboy** [devopsgroup-io/vagrant-hostmanager#225]
```
Lukes-MacBook-Pro-2:trellis lukemackenzie$ vagrant plugin install vagrant-hostmanager
Installing the 'vagrant-hostmanager' plugin. This can take a few minutes...
Installed the plugin 'vagrant-hostmanager (1.8.5)'!
Lukes-MacBook-Pro-2:trellis lukemackenzie$ vagrant up --provision
vagrant-hostmanager missing, please install the plugin with this command:
vagrant plugin install vagrant-hostmanager

Or install landrush for multisite subdomains:
vagrant plugin install landrush
```

vagrant can't see the hostmanager plugin even though I have installed it. Vagrant 1.8.6 after a complete purge of all vagrant files on my OSX system

I downgraded to 1.8.6 due to an incompatibility issue with the landrush plugin. I've tried installing and uninstalling both hostmanager and landrush

**Comment by seth-reeser** [comment]
Please run `sudo rm -Rf ~/.vagrant.d/gems/ && sudo rm ~/.vagrant.d/plugins.json` and then try and reinstall `vagrant plugin install vagrant-hostmanager`. If you continue to have issue, please reopen this issue.

**Comment by kirkbross** [comment]
Removing the gems and plugins.json worked for me in Windows 10.

**Comment by v3ritas1989** [comment]
@seth-reeser whats the command in windows?

**Comment by vineethvijay** [comment]
This does not work in vagrant 2.1.3, 2.1.4
Had to downgrade to 2.1.2

**Comment by v3ritas1989** [comment]
that works, thanks

**Comment by weblid** [comment]
I had to downgrade to 2.1.1.

**Comment by jsaxestaral** [comment]
Upgrade to 2.1.5 resolved issue

**Comment by v3ritas1989** [comment]
can confirm 2.1.5 resolved the issue
