### ISSUE TITLE
vagrant plugin install can't find latest release from rubygems.org

### ISSUE THREAD

**Issue by bradchoate** [devopsgroup-io/vagrant-hostmanager#227]
Maybe I'm missing something, but Vagrant 1.9.2 is using two sources for gems: rubygems.org and gems.hashicorp.com. Between them, only rubygems.org lists vagrant-hostmanager, and it only has version 0.8.1, not the latest 1.8.5 release.

The 0.8.1 version won't install due to a childprocess module mismatch (it wants 0.3.9, but 0.5.9 is activated).

The README for this project just states to use the `vagrant plugin install vagrant-hostmaster` command to install, without overriding the plugin sources or anything special, so I'm not sure what I'm doing wrong.

Running Mac OS El Sierra (10.12.3), Vagrant 1.9.2 (new install).

**Comment by seth-reeser** [comment]
Hi @bradchoate RubyGems does have the latest https://rubygems.org/gems/vagrant-hostmanager

Try a `vagrant plugin uninstall` followed by a `vagrant plugin install` and please reopen this issue if you continue to have problems.

Also take a look at the referenced issue to see if that helps - https://github.com/mitchellh/vagrant/issues/8455
