### ISSUE TITLE
Permission denied @ rb_sysopen - .vagrant.d/tmp/hosts.local

### ISSUE THREAD

**Issue by tovletoglou** [devopsgroup-io/vagrant-hostmanager#233]
On a Windows system, runing the `vagrant up`, I'm getting the error:

```shell
C:/Users/USER/.vagrant.d/gems/2.2.5/gems/vagrant-hostmanager-1.8.6/lib/vagrant-hostmanager/hosts_file/updater.rb:85:in `initialize': Permission denied @ rb_sysopen - C:/Users/USER/.vagrant.d/tmp/hosts.local (Errno::EACCES)
```

Checking the file `C:/Users/USER/.vagrant.d/tmp/hosts.local` and it's read-only.

Then run the `vagrant up` again:

```shell
C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/fileutils.rb:1392:in `initialize': Permission denied @ rb_sysopen - C:/Users/USER/.vagrant.d/tmp/hosts.local (Errno::EACCES)
```

Example Vagrantfile

```Ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.provider 'virtualbox' do |vb|
    vb.gui = false
    vb.memory = '1024'
    vb.cpus = 1
  end
  config.vm.box = 'centos/7'
  config.vm.synced_folder '.',
                          '/vagrant',
                          type: 'vboxsf',
                          disabled: true
  config.vm.hostname = "my_hostname"
  config.vm.network "private_network", ip: "192.168.33.10"
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.manage_guest = true
  config.hostmanager.ignore_private_ip = false
  config.hostmanager.include_offline = true
end
```

System:
Windows 10
Vagrant 1.9.3
vagrant-hostmanager 1.8.6

**Comment by Ovsyanka** [comment]
I removed "read-only" attribute frome the hosts file and it worked for me.
But I think that it is temporary solution and things should work without it.

**Comment by xymox12** [comment]
This was my workaround which I am currently using successfully (so far!):

https://github.com/devopsgroup-io/vagrant-hostmanager/issues/178#issuecomment-518195409

**Comment by tovletoglou** [comment]
Close issue due to inactivity

**Comment by tino118** [comment]
1. don't use the plugin host updater.

vagrant plugin list
vagrant plugin uninstall <name>

2. Make sure your user without elevating privileges have access to read
write to:
C:/Windows/system32/drivers/etc/hosts

**Comment by michalziaja** [comment]
> 1. don't use the plugin host updater.
> 
> vagrant plugin list vagrant plugin uninstall
> 
> 2. Make sure your user without elevating privileges have access to read
>    write to:
>    C:/Windows/system32/drivers/etc/hosts

This helps. Thank You!

**Comment by Gabi0022** [comment]
What helped me was:
Delete hosts.local file from .vagrant.d\tmp
Go to C:/Windows/system32/drivers
Disable read only from etc/ folder and all its components

**Comment by Slider2019** [comment]
Got the error:

```Shell
C:/Program Files/Vagrant/embedded/mingw64/lib/ruby/3.3.0/fileutils.rb:2278:in `initialize': No such file or directory @ rb_sysopen - C:\Windows\System32\drive
rs\etc\hosts (Errno::ENOENT)
```

Next error few lines below:

```Shell
C:/Program Files/Vagrant/embedded/mingw64/lib/ruby/3.3.0/fileutils.rb:2278:in `initialize': No such file or directory @ rb_sysopen - C:\Windows\System32\drive
rs\etc\hosts (Errno::ENOENT)
```


What helped me was:

1. Go to: C:\Windows\System32\drivers\etc
2. Delete hosts file
3. Re create the host file by opening notepad and paste this:

```
# Copyright (c) 1993-2006 Microsoft Corp.
#
# This is a sample HOSTS file used by Microsoft TCP/IP for Windows.
#
# This file contains the mappings of IP addresses to host names. Each
# entry should be kept on an individual line. The IP address should
# be placed in the first column followed by the corresponding host name.
# The IP address and the host name should be separated by at least one
# space.
#
# Additionally, comments (such as these) may be inserted on individual
# lines or following the machine name denoted by a '#' symbol.
#
# For example:
#
# 102.54.94.97 rhino.acme.com # source server
# 38.25.63.10 x.acme.com # x client host
# localhost name resolution is handle within DNS itself.
# 127.0.0.1 localhost
# ::1 localhost
```

4. Reboot and then vagrant up
