### ISSUE TITLE
Unknown configuration section 'hostmanager'.

### ISSUE THREAD

**Issue by dbstraffin** [devopsgroup-io/vagrant-hostmanager#268]
Using vagrant 2.1.3 and vagrant-hostmanager 1.8.8 and 1.8.9, I get the following error:
```
There are errors in the configuration of this machine. Please fix
the following errors and try again:

Vagrant:
* Unknown configuration section 'hostmanager'.
```

I tried `vagrant plugin update`, `vagrant plugin repair` and `vagrant plugin expunge`, none of which fixed the issue.

Downgrading to vagrant 2.1.2 fixed the issue and people are having issues with other plugins, so it might actually be a problem with vagrant 2.1.3.
https://github.com/hashicorp/vagrant/issues/10150
https://github.com/hashicorp/vagrant/issues/10161

**Comment by chrisroberts** [comment]
Hi there,

This was a Vagrant issue and was fixed via hashicorp/vagrant#10155

**Comment by dbstraffin** [comment]
Looks like Vagrant 2.1.4 fixes this issue for me.

**Comment by bobweston** [comment]
I'm seeing the same error in Vagrant 2.2.5

**Comment by alykov1** [comment]
> I'm seeing the same error in Vagrant 2.2.5
try 
# vagrant plugin install vagrant-hostmanager

**Comment by emranhossain2022** [comment]
Error message:
$ Vagrant up
bash: vagrant: command not found

or Error message:
Vagrant:
* Unknown configuration section 'hostmanager'.

Solutions:

Step one: 
On your host machine you need to install VirtualBox and the VirtualBox is a hypervisor that helps you to build Virtual Machine.

Step two:
If you have Hyper-V hypervisor in your PC, first, you disable it.
Right-click > Windows Power Shell > Run as administrator > Copy the Below command

`Disable-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V-All`
		
*execute the code with power shell and Your Hyper-V will disable

Step three:
Download the [Vagrant installer](https://releases.hashicorp.com/vagrant/2.2.9/vagrant_2.2.9_x86_64.msi) and install it on your windows machine.

Step Four:
Now you can execute your “vagrant up” Command using Git Bash. Just type the following command to verify Vagrant.
	`$ vagrant --version`
	`$ git --version`
Step Five:
Need to install the Vagrant plugin. Execute the below command by Git Bash
	`$ vagrant plugin install vagrant-hostmanager`

And finally, execute this one.

	`$ vagrant up`

**Comment by bilal-07** [comment]
$ vagrant plugin install vagrant-hostmanager

This Work for me!!!!

**Comment by AdityaKabu** [comment]
> vagrant plugin install vagrant-hostmanager

Thank you! worked for me.

**Comment by William-eng** [comment]
Need to install the Vagrant plugin. Execute the below command by Git Bash
$ vagrant plugin install vagrant-hostmanager
$ vagrant reload
$ vagrant up

**Comment by Emmanuelaina** [comment]
$ vagrant plugin install vagrant-hostmanager


worked for me. Thanks so much.
