### ISSUE TITLE
Updating guest fails on vagrant >= 2.3.5

### ISSUE THREAD

**Issue by stephenreay** [devopsgroup-io/vagrant-hostmanager#290]
Vagrant 2.3.5 moved to shipping Ruby3; 

When updating the guest, an error is thrown from `update_guest.rb:20`, due to [this change](https://rubyreferences.github.io/rubychanges/3.0.html#keyword-arguments-are-now-fully-separated-from-positional-arguments).

**Comment by wimsymons** [comment]
Who can merge and release this?

**Comment by wimsymons** [comment]
According to https://rubygems.org/gems/vagrant-hostmanager, that is @seth-reeser or @smdahlen. Can you guys take a look? 🙏

**Comment by zipkid** [comment]
It's a bit early in the USA a.t.m... hopefully they will wake up soon.

**Comment by wimsymons** [comment]
Thank you very much for the merge, but a new release is needed as well to make it work on vagrant 2.3.5+.

Can you make this happen?

**Comment by wimsymons** [comment]
@seth-reeser thank you for 1.8.10! Much appreciated 😀
